var genres = {
  "African": [
    "african",
    "african heavy metal",
    "african hip hop",
    "afrobeat",
    "apala",
    "benga",
    "bongo flava",
    "bikutsi",
    "cape jazz",
    "chimurenga",
    "congolese rumba",
    "coupé-décalé",
    "fuji music",
    "genge",
    "highlife",
    "hiplife",
    "igbo highlife",
    "igbo rap",
    "isicathamiya",
    "jit",
    "jùjú",
    "kapuka",
    "kadongo kamu",
    "kizomba",
    "kuduro",
    "kwaito",
    "kwela",
    "makossa",
    "maloya",
    "marrabenta",
    "mbalax",
    "mbaqanga",
    "mbube",
    "morna",
    "ndombolo",
    "palm-wine",
    "raï",
    "sakara",
    "sega",
    "seggae",
    "semba",
    "shangaan electro",
    "soukous",
    "kwassa kwassa",
    "taarab",
    "zouglou"
  ],
  "Asian": [
    "asian",
    "fann at-tanbura",
    "fijiri",
    "khaliji",
    "liwa",
    "sawt"
  ],
  "South Asian": [
    "south asian",
    "baila",
    "baul",
    "bhangra",
    "dangdut",
    "filmi",
    "indian pop",
    "lavani",
    "luk thung",
    "luk krung",
    "manila sound",
    "original pilipino music",
    "v-pop",
    "morlam",
    "pinoy pop",
    "pop sunda",
    "thai pop",
    "ragini",
    "keroncong",
    "gamelan"
  ],
  "Avant-Garde": [
    "avant-garde",
    "experimental music",
    "noise",
    "lo-fi",
    "musique concrète",
    "electroacoustic"
  ],
  "Blues": [
    "blues",
    "african blues",
    "blues rock",
    "blues shouter",
    "british blues",
    "canadian blues",
    "chicago blues",
    "classic female blues",
    "contemporary r&b",
    "country blues",
    "delta blues",
    "detroit blues",
    "electric blues",
    "gospel blues",
    "hill country blues",
    "hokum blues",
    "jump blues",
    "kansas city blues",
    "louisiana blues",
    "memphis blues",
    "piedmont blues",
    "punk blues",
    "rhythm and blues",
    "soul blues",
    "st. louis blues",
    "swamp blues",
    "texas blues",
    "west coast blues",
    "new orleans blues",
    "modern blues",
    "blues",
    "traditional blues",
    "acoustic blues",
    "piano blues"
  ],
  "Caribbean": [
    "carribean",
    "baithak gana",
    "dancehall music",
    "bouyon",
    "cadence-lypso",
    "calypso",
    "cha cha cha",
    "chutney",
    "chutney soca",
    "compas",
    "mambo",
    "merengue",
    "méringue",
    "mosambique",
    "punta",
    "punta rock",
    "rasin",
    "reggae",
    "dancehall",
    "dub",
    "lovers rock",
    "ragga",
    "ragga jungle",
    "reggae fusion",
    "reggaeton",
    "rocksteady",
    "rumba",
    "ska",
    "2 tone",
    "ska punk",
    "salsa",
    "son cubano",
    "songo",
    "soca",
    "timba",
    "twoubadou",
    "zouk",
    "roots reggae",
    "rock steady",
    "swedish reggae"
  ],
  "Comedy": [
    "comedy"
  ],
  "Country": [
    "country",
    "alternative country",
    "cowpunk",
    "blues country",
    "hokum",
    "outlaw country",
    "progressive country",
    "zydeco",
    "country rap",
    "red dirt",
    "rockabilly",
    "hellbilly music",
    "psychobilly/punkabilly",
    "country rock",
    "texas country",
    "americana",
    "australian country music",
    "bakersfield sound",
    "bluegrass",
    "progressive bluegrass",
    "reactionary bluegrass",
    "cajun",
    "cajun fiddle tunes",
    "christian country music",
    "classic country",
    "close harmony",
    "dansband music",
    "franco-country",
    "honky tonk",
    "instrumental country",
    "nashville sound",
    "neotraditional country",
    "country pop",
    "sertanejo",
    "traditional country music",
    "truck-driving country",
    "western swing"
  ],
  "Easy Listening": [
    "easy listening",
    "background music",
    "beautiful music",
    "elevator music",
    "furniture music",
    "lounge music",
    "middle of the road",
    "new-age music"
  ],
  "Electronic": [
    "electronic",
    "ambient",
    "ambient dub",
    "dark ambient",
    "drone music",
    "space music",
    "illbient",
    "psybient",
    "isolationism",
    "lowercase",
    "asian underground",
    "breakbeat",
    "acid breaks",
    "baltimore club",
    "big beat",
    "broken beat",
    "florida breaks",
    "nu-funk",
    "miami bass",
    "jersey club",
    "nu skool breaks",
    "disco",
    "afro / cosmic disco",
    "disco polo",
    "euro disco",
    "italo disco",
    "nu-disco",
    "space disco",
    "downtempo",
    "acid jazz",
    "chill-out",
    "new-age music",
    "space music",
    "trip hop",
    "drum and bass",
    "darkstep",
    "drill and bass",
    "drumstep",
    "funkstep",
    "hardstep",
    "jump-up",
    "liquid funk",
    "neurofunk",
    "neurohop",
    "sambass",
    "techstep",
    "dub",
    "electro music",
    "freestyle music",
    "electroacoustic music",
    "acousmatic music",
    "musique concrète",
    "electronic rock",
    "alternative dance",
    "indietronica",
    "coldwave",
    "dance-punk",
    "dark wave",
    "electroclash",
    "electronicore",
    "electropunk",
    "ethereal wave",
    "krautrock",
    "minimal wave",
    "new rave",
    "nu-gaze",
    "space rock",
    "synthpop",
    "synthwave",
    "electronica",
    "berlin school",
    "dubtronica",
    "ethnic electronica",
    "folktronica",
    "funktronica",
    "laptronica",
    "livetronica",
    "hardcore",
    "gabba",
    "4-beat",
    "breakbeat hardcore",
    "bouncy techno",
    "breakcore",
    "digital hardcore",
    "darkcore",
    "happy hardcore",
    "mákina",
    "speedcore",
    "uk hardcore",
    "doomcore",
    "hardstyle",
    "dubstyle",
    "jumpstyle",
    "lento violento",
    "hi-nrg",
    "eurobeat",
    "eurodance",
    "bubblegum dance",
    "italo dance",
    "house music",
    "acid house",
    "ambient house",
    "balearic beat",
    "chicago house",
    "deep house",
    "future house",
    "tropical house",
    "bouncy house",
    "diva house",
    "electro house",
    "big room",
    "complextro",
    "melbourne bounce",
    "fidget house",
    "dutch house",
    "moombahton",
    "moombahcore",
    "electro swing",
    "french house",
    "funky house",
    "garage house",
    "ghetto house",
    "ghettotech",
    "hardbag",
    "hard house",
    "hard nrg",
    "nu-nrg",
    "hip house",
    "italo house",
    "jazz house",
    "kwaito",
    "latin house",
    "microhouse",
    "new beat",
    "outsider house",
    "progressive house",
    "rara tech",
    "tech house",
    "tribal house",
    "trival",
    "witch house",
    "industrial music",
    "aggrotech",
    "cybergrind",
    "electro-industrial",
    "dark electro",
    "electronic body music",
    "futurepop",
    "industrial metal",
    "industrial rock",
    "japanoise",
    "neue deutsche härte",
    "power electronics",
    "death industrial",
    "power noise",
    "idm",
    "glitch",
    "glitch hop",
    "wonky",
    "jungle",
    "darkcore jungle",
    "raggacore",
    "post-disco",
    "boogie",
    "electropop",
    "chillwave",
    "dance-pop",
    "dance-rock",
    "techno",
    "acid techno",
    "detroit techno",
    "dub techno",
    "free tekno",
    "minimal techno",
    "nortec",
    "tecno brega",
    "techdombe",
    "trance music",
    "acid trance",
    "balearic trance",
    "dream trance",
    "goa trance",
    "hard trance",
    "nitzhonot",
    "psychedelic trance",
    "suomisaundi",
    "full on",
    "progressive trance",
    "tech trance",
    "uplifting trance",
    "vocal trance",
    "uk garage",
    "2-step garage",
    "dubstep",
    "brostep",
    "chillstep",
    "reggaestep",
    "trapstep",
    "liquid dubstep",
    "neurohop",
    "breakstep",
    "future garage",
    "grime",
    "grindie",
    "speed garage",
    "bassline",
    "uk funky",
    "vaporwave",
    "video game music",
    "chiptune",
    "bitpop",
    "game boy music",
    "skweee",
    "nintendocore",
    "electronic",
    "deep disco house",
    "minimal tech house",
    "disco house",
    "float house",
    "deep melodic euro house",
    "house",
    "nu disco",
    "bass music",
    "balearic",
    "ninja",
    "filter house",
    "french indietronica",
    "vocal house",
    "deep euro house",
    "electro jazz",
    "deep groove house",
    "hardcore techno",
    "deep soul house",
    "intelligent dance music",
    "latin electronica",
    "jump up",
    "chamber psych",
    "edm",
    "vapor twitch",
    "funky breaks",
    "electronic trap",
    "german techno",
    "drumfunk",
    "fluxwork",
    "chill lounge",
    "electro",
    "substep",
    "deep downtempo fusion",
    "deep funk house",
    "deep disco",
    "electro dub",
    "aussietronica",
    "deep liquid"
  ],
  "Folk": [
    "folk",
    "american folk revival",
    "anti-folk",
    "british folk revival",
    "celtic music",
    "chalga",
    "contemporary folk",
    "filk music",
    "folktronica",
    "freak folk",
    "indie folk",
    "industrial folk",
    "neofolk",
    "progressive folk",
    "protest song",
    "psychedelic folk",
    "singer-songwriter",
    "skiffle",
    "sung poetry",
    "cowboy/western music",
    "folk-pop",
    "folk",
    "lilith",
    "traditional folk"
  ],
  "Hip Hop": [
    "hip hop",
    "alternative hip hop",
    "australian hip hop",
    "bongo flava",
    "british hip hop",
    "chap hop",
    "christian hip hop",
    "conscious hip hop",
    "crunk",
    "crunkcore",
    "drill",
    "east coast hip hop",
    "baltimore club",
    "brick city club",
    "hardcore hip hop",
    "mafioso rap",
    "new jersey hip hop",
    "electro music",
    "experimental hip hop",
    "ghetto house",
    "ghettotech",
    "golden age hip hop",
    "grime",
    "hardcore hip hop",
    "hip house",
    "hiplife",
    "hip pop",
    "industrial hip hop",
    "instrumental hip hop",
    "kwaito",
    "lyrical hip hop",
    "low bap",
    "midwest hip hop",
    "chicago hip hop",
    "ghetto house",
    "detroit hip hop",
    "ghettotech",
    "st. louis hip hop",
    "twin cities hip hop",
    "horrorcore",
    "merenrap",
    "motswako",
    "nerdcore",
    "new jack swing",
    "new school hip hop",
    "old school hip hop",
    "political hip hop",
    "ragga",
    "reggaeton",
    "rap music",
    "country-rap",
    "cumbia rap",
    "freestyle rap",
    "gangsta rap",
    "igbo rap",
    "jazz rap",
    "rap opera",
    "rap rock",
    "rapcore",
    "rap metal",
    "reggae español/spanish reggae",
    "southern hip hop",
    "atlanta hip hop",
    "snap music",
    "bounce music",
    "crunk",
    "houston hip hop",
    "chopped and screwed",
    "miami bass",
    "songo-salsa",
    "trap",
    "trip hop",
    "turntablism",
    "underground hip hop",
    "urban pasifika",
    "west coast hip hop",
    "chicano rap",
    "g-funk",
    "hyphy",
    "jerkin'",
    "hip hop",
    "rap",
    "gangster rap",
    "urban contemporary",
    "quiet storm",
    "dirty south rap",
    "trap music",
    "chillhop",
    "escape room",
    "west coast rap",
    "g funk",
    "ambeat",
    "uk hip hop",
    "underground rap",
    "abstract beats",
    "abstract hip hop",
    "french reggae",
    "bass trip",
    "scratch",
    "french hip hop",
    "german hip hop",
    "new tribe",
    "dutch hip hop",
    "outer hip hop",
    "beatdown",
    "canadian hip hop",
    "brazilian hip hop"
  ],
  "Jazz": [
    "jazz",
    "acid jazz",
    "afro-cuban jazz",
    "asian american jazz",
    "avant-garde jazz",
    "bebop",
    "boogie-woogie",
    "bossa nova",
    "british dance band",
    "cape jazz",
    "chamber jazz",
    "continental jazz",
    "cool jazz",
    "crossover jazz",
    "dixieland",
    "ethno jazz",
    "european free jazz",
    "free funk",
    "free improvisation",
    "free jazz",
    "gypsy jazz",
    "hard bop",
    "jazz blues",
    "jazz-funk",
    "jazz fusion",
    "jazz rap",
    "jazz rock",
    "kansas city blues",
    "kansas city jazz",
    "latin jazz",
    "livetronica",
    "m-base",
    "mainstream jazz",
    "modal jazz",
    "neo-bop jazz",
    "neo-swing",
    "novelty ragtime",
    "nu jazz",
    "orchestral jazz",
    "post-bop",
    "punk jazz",
    "ragtime",
    "shibuya-kei",
    "ska jazz",
    "smooth jazz",
    "soul jazz",
    "stride jazz",
    "straight-ahead jazz",
    "swing",
    "third stream",
    "trad jazz",
    "vocal jazz",
    "west coast jazz",
    "jazz",
    "contemporary jazz",
    "compositional ambient"
  ],
  "Latin": [
    "latin",
    "brazilian",
    "axé",
    "brazilian rock",
    "brega",
    "tecnobrega",
    "choro",
    "forró",
    "frevo",
    "funk carioca",
    "lambada",
    "zouk-lambada",
    "maracatu",
    "música popular brasileira",
    "tropicalia",
    "música sertaneja",
    "samba",
    "pagode",
    "samba rock",
    "latin christian",
    "latin jazz",
    "afro-cuban jazz",
    "bossa nova",
    "latin pop",
    "latin ballad",
    "latin swing",
    "latin rock",
    "latin alternative",
    "rock en español",
    "reggaeton",
    "regional mexican",
    "banda",
    "grupera",
    "mariachi",
    "ranchera",
    "norteño",
    "tejano",
    "flamenco",
    "tango",
    "bullerengue",
    "fado",
    "huayno",
    "mexican son",
    "música criolla",
    "nueva canción",
    "tropical",
    "bachata",
    "bolero",
    "criolla",
    "cumbia",
    "chicha",
    "porro",
    "guajira",
    "mambo",
    "merengue",
    "rumba",
    "salsa",
    "salsa romántica",
    "son",
    "timba",
    "tropipop",
    "vallenato",
    "nu-cumbia",
    "latin",
    "boogaloo"
  ],
  "Pop": [
    "pop",
    "adult contemporary",
    "arab pop",
    "baroque pop",
    "brill building",
    "britpop",
    "bubblegum pop",
    "canción",
    "canzone",
    "chalga",
    "chanson",
    "christian pop",
    "classical crossover",
    "country pop",
    "c-pop",
    "mandopop",
    "dance-pop",
    "disco polo",
    "electropop",
    "europop",
    "austropop",
    "eurobeat",
    "french pop",
    "italo dance",
    "italo disco",
    "laïkó",
    "latin pop",
    "nederpop",
    "russian pop",
    "fado",
    "folk pop",
    "iranian pop",
    "indie pop",
    "j-pop",
    "jangle pop",
    "k-pop",
    "latin ballad",
    "louisiana swamp pop",
    "mexican pop",
    "new romanticism",
    "operatic pop",
    "pop rap",
    "pop rock",
    "power pop",
    "soft rock",
    "pop soul",
    "progressive pop",
    "psychedelic pop",
    "rebetiko",
    "schlager",
    "sophisti-pop",
    "space age pop",
    "sunshine pop",
    "surf pop",
    "synthpop",
    "teen pop",
    "traditional pop music",
    "turkish pop",
    "vispop",
    "wonky pop",
    "worldbeat",
    "shimmer pop",
    "pop",
    "chamber pop",
    "noise pop",
    "dance pop",
    "new wave pop",
    "brill building pop",
    "polynesian pop",
    "french indie pop",
    "mande pop",
    "boy band",
    "stomp pop",
    "canadian pop",
    "acoustic pop",
    "danish pop"
  ],
  "R&B/Soul": [
    "r&b/soul",
    "contemporary r&b",
    "disco",
    "funk",
    "deep funk",
    "freestyle music",
    "go-go",
    "hip hop soul",
    "p-funk",
    "post-disco",
    "boogie",
    "new jack swing",
    "rhythm and blues",
    "soul",
    "blue-eyed soul",
    "hip hop soul",
    "northern soul",
    "neo soul",
    "southern soul",
    "r&b",
    "classic funk rock",
    "motown",
    "memphis soul",
    "chicago soul",
    "jazz funk",
    "neo mellow",
    "deep indie r&b",
    "vapor soul",
    "deep pop r&b",
    "brass band",
    "traditional soul",
    "traditional funk"
  ],
  "Rock": [
    "rock",
    "alternative rock",
    "grunge",
    "post-grunge",
    "indie rock",
    "dunedin sound",
    "post-punk revival",
    "sadcore",
    "dream pop",
    "shoegaze",
    "slowcore",
    "beat music",
    "chinese rock",
    "christian rock",
    "dark cabaret",
    "electronicore",
    "electronic rock",
    "experimental rock",
    "art rock",
    "industrial rock",
    "post-punk",
    "gothic rock",
    "no wave",
    "noise rock",
    "post-rock",
    "post-metal",
    "folk rock",
    "garage rock",
    "glam rock",
    "hard rock",
    "heavy metal",
    "alternative metal",
    "avant-garde metal",
    "black metal",
    "symphonic black metal",
    "viking metal",
    "war metal",
    "christian metal",
    "unblack metal",
    "death metal",
    "death 'n' roll",
    "melodic death metal",
    "technical death metal",
    "goregrind",
    "doom metal",
    "death-doom",
    "drone metal",
    "folk metal",
    "celtic metal",
    "medieval metal",
    "pagan metal",
    "funk metal",
    "glam metal",
    "gothic metal",
    "grindcore",
    "industrial metal",
    "latin metal",
    "metalcore",
    "melodic metalcore",
    "deathcore",
    "mathcore",
    "neoclassical metal",
    "nu metal",
    "post-metal",
    "power metal",
    "progressive metal",
    "djent",
    "rap metal",
    "sludge metal",
    "speed metal",
    "symphonic metal",
    "thrash metal",
    "crossover thrash",
    "groove metal",
    "jazz rock",
    "math rock",
    "neue deutsche härte",
    "new wave",
    "world fusion",
    "paisley underground",
    "desert rock",
    "pop rock",
    "soft rock",
    "progressive rock",
    "canterbury scene",
    "krautrock",
    "new prog",
    "rock in opposition",
    "space rock",
    "psychedelic rock",
    "acid rock",
    "freakbeat",
    "neo-psychedelia",
    "neo-psychedelic",
    "raga rock",
    "punk rock",
    "anarcho punk",
    "crust punk",
    "d-beat",
    "art punk",
    "christian punk",
    "deathrock",
    "digital hardcore",
    "folk punk",
    "celtic punk",
    "cowpunk",
    "gypsy punk",
    "garage punk",
    "grindcore",
    "crustgrind",
    "noisegrind",
    "hardcore punk",
    "post-hardcore",
    "emo",
    "screamo",
    "thrashcore",
    "crossover thrash",
    "powerviolence",
    "street punk",
    "horror punk",
    "pop punk",
    "psychobilly",
    "riot grrrl",
    "ska punk",
    "skate punk",
    "rap rock",
    "rapcore",
    "rock and roll",
    "southern rock",
    "stoner rock",
    "sufi rock",
    "surf rock",
    "visual kei",
    "nagoya kei",
    "worldbeat",
    "modern rock",
    "indie r&b",
    "indie jazz",
    "rock",
    "permanent wave",
    "blues-rock",
    "mellow gold",
    "indie psych-rock",
    "classic rock",
    "funk rock",
    "album rock",
    "roots rock",
    "dance rock",
    "madchester",
    "adult standards",
    "new romantic",
    "stomp and holler",
    "rock-and-roll",
    "punk",
    "protopunk",
    "nu gaze",
    "slow core",
    "garage psych",
    "melancholia",
    "uk post-punk",
    "kiwi rock",
    "jam band",
    "british invasion",
    "deep australian indie",
    "australian alternative rock",
    "alt-indie rock",
    "chilean rock",
    "deep german punk",
    "portuguese rock",
    "canadian indie",
    "albuquerque indie",
    "neo-progressive",
    "argentine rock",
    "austindie"
  ],
  "World": [
    "world"
  ]
};